<?php 
	function projects(){
		$projects = [];
		$projects[] = ['title'=> 'Dithermark', 'completion_date'=> '2018-08-01', 'github'=> 'dithermark', 'url'=> 'https://dithermark.com', 'logo_url'=> 'dithermark-icon.svg', 'description'=> 'Web application that allows you to easily create original pixel art. Includes variations on many popular image dithering algorithms, as well as original color quantization algorithm research. Uses <a href="https://vuejs.org/">Vue.js</a>, the <a href="https://unsplash.com/developers">Unsplash photo API</a> and modern JavaScript features such as: ES6 syntax, webworkers, canvas API, and WebGL.'];
		$projects[] = ['title'=> 'Artour', 'completion_date'=> '2017-03-10', 'github'=> 'artour', 'url'=> 'https://strangescenery.com', 'logo_url'=> 'artour-icon.svg', 'description'=> 'Custom CMS, blog engine and static site generator specifically designed for artwork and photography blogs. Made with <a href="http://elixir-lang.org/">Elixir</a> and the <a href="http://www.phoenixframework.org/">Phoenix Framework.</a> Features include: separate admin section, custom tags and categories, multiple image asset size support, organizing images in albums using drag-and-drop, and image carousels with optional captions and lazy asset loading.'];
		// $projects[] = ['title'=> 'H-News', 'completion_date'=> '2015-06-28', 'github'=> 'h-news', 'url'=> 'http://hnews.co', 'logo_url'=> 'h-news-icon.svg', 'description'=> 'I love reading <a href="https://news.ycombinator.com/">Hacker News</a> for the latest software development and technology news, but the text is too small, and it is hard to use on mobile. I created a redesigned version to address these issues using the <a href="https://github.com/HackerNews/API">official API</a> to pull in the latest story and comment data through AJAX. I also added the ability for readers to pick a custom color theme that is saved using the browser localStorage.'];
		$projects[] = ['title'=> 'CSV Parser', 'completion_date'=> '2016-04-25', 'github'=> 'csv-parser-js',  'logo_url'=> 'csv-parser-icon.svg', 'description'=> 'CSV parser written in JavaScript that is currently being used in production as part of a corporate LMS (learning management system). Compatible with the CSV output from Excel, Google Sheets, and Apple Numbers and can be used either in the browser or on a server using <a href="https://nodejs.org">Node.js.</a> Includes unit tests using the <a href="https://jasmine.github.io/index.html">Jasmine test framework.</a>'];
		// $projects[] = ['title'=> 'Earscape', 'completion_date'=> '2015-08-22', 'github'=> 'earscape', 'url'=> 'https://allen-garvey.github.io/earscape/', 'logo_url'=> 'earscape-icon.png', 'description'=> 'One of my interests is the intersection of music with technology (particularly algorithmic composition), so I created this web app to generate random twelve tone melodies. I used <a href="https://github.com/meenie/band.js">Band.js</a> to play the melodies and <a href="https://github.com/0xfe/vextab">VexTab</a> to output the sheet music.'];


		return $projects;
	}
 ?>